# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {IP_Flow 19-1663}  -string {{CRITICAL WARNING: [IP_Flow 19-1663] Duplicate IP found for 'DigilentInc:user:Digi_LED:1.0'. The one found in IP location '/home/marshall/workspace/ip_repo/Digi_LED_1.0' will take precedence over the same IP in location /home/marshall/workspace/ip_repo/edit_Digi_LED_v1_0.srcs/sources_1/imports/Digi_LED_1.0}}  -suppress 

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.cache/wt [current_project]
set_property parent.project_path /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/marshall/workspace/ip_repo [current_project]
add_files /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/ipshared/digilentinc.com/dvi2rgb_v1_4/4f0fd262/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/ipshared/digilentinc.com/dvi2rgb_v1_4/4f0fd262/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /home/marshall/workspace/support/hdmi_passthrough_720p/hdmi_passthrough_720p.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc /home/marshall/Downloads/ZYBO_Master.xdc
set_property used_in_implementation false [get_files /home/marshall/Downloads/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
